name: PDX203-FINAL-DIRECT-LINK
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential clang llvm lld libssl-dev git python3-minimal gcc-aarch64-linux-gnu zlib1g-dev libelf-dev curl

      - name: Build
        run: |
          export ARCH=arm64
          printf "\nCONFIG_INPUT_TOUCHSCREEN=y\nCONFIG_TOUCHSCREEN_SYNAPTICS_DSX=y\nCONFIG_TOUCHSCREEN_FTS=y\nCONFIG_TOUCHSCREEN_COMMON=y\n" >> arch/arm64/configs/pdx203_defconfig
          make O=out pdx203_defconfig
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- KBUILD_WERROR=0 KCFLAGS="-w -fcommon"

      - name: Upload and Give Link
        run: |
          # Dosyayı out klasörü içinde her yerde ara
          KERNEL_PATH=$(find out/ -name "Image.gz" | head -n 1)
          if [ -z "$KERNEL_PATH" ]; then
            echo "Kritik Hata: Kernel dosyasi hic olusmadi!"
            exit 1
          fi
          echo "--- DOSYA BULUNDU, LINK ALINIYOR ---"
          # Transfer.sh'ye yükle ve sonucu bekle
          RESULT_LINK=$(curl --upload-file "$KERNEL_PATH" https://transfer.sh/Xperia_1_II_Kernel.gz)
          echo "************************************************"
          echo "INDIRME LINKIN BURADA: $RESULT_LINK"
          echo "************************************************"
